name: Docker CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      main

jobs:
  docker-build:
    strategy:
      matrix:
        version: ['1.16','1.17','1.18','1.18-terra']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: go
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # image: cultclassik/go-builder
          # password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ matrix.version }}-${{ github.sha }}
          tag_with_latest: false
          # cache: true
          # cache_registry: cache
          # skip_unchanged_digest: true
          strip_tag_prefix: v
          build_file: ${{ matrix.version }}/Dockerfile

  # docker-scan:
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          # image-ref: cultclassik/go-builder:${{ matrix.version }}-${{ github.sha }}
          image-ref: ghcr.io/diehlabs/go-builder/go:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
