name: Docker Build & Release

on:
  push:
    branches:
      main
    workflow_dispatch:

jobs:
  docker-build:
    strategy:
      matrix:
        version: ['1.16','1.17','1.18','1.18-terra']
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.tag_version.outputs.new_tag }}

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          # image: go-builder
          # registry: ghcr.io
          # password: ${{ secrets.GITHUB_TOKEN }}
          image: cultclassik/go-builder
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ steps.tag_version.outputs.new_tag }}-${{ matrix.version }}
          tag_with_latest: true
          build_file: ${{ matrix.version }}/Dockerfile
          # cache: true
          # cache_registry: cache
          # skip_unchanged_digest: true

  # docker-scan:
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cultclassik/go-builder:${{ steps.tag_version.outputs.new_tag }}-${{ matrix.version }}
          # image-ref: ghcr.io/diehlabs/go-builder:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
